CREATE TABLE `CCNOA`.`MARKDOWN` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MARKDOWN_ID` VARCHAR(200) NOT NULL,
  `MARKDOWN_USER` VARCHAR(45) NULL,
  `MARKDOWN_ITEM` VARCHAR(500) NOT NULL,
  `MARKDOWN_KEYWORDS` VARCHAR(500) NOT NULL,
  `MARKDOWN_TIME` TIMESTAMP NOT NULL,  
  `MARKDOWN_SUGGESTION` VARCHAR(500) NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE `CCNOA`.`RECOMMEND` (
  `RECOMMEND_ID` INT NOT NULL,
  `RECOMMEND_KEYWORDS` VARCHAR(500) NOT NULL,
  `RECOMMEND_ITEM` VARCHAR(500) NOT NULL,
  `RECOMMEND_EVALUATE` VARCHAR(10) NULL,
  `RECOMMEND_TIME` TIMESTAMP NOT NULL,
  `MARKDOWN_ID` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`RECOMMEND_ID`));
